services:
  keycloak-postgres:
    image: postgres:15.15
    volumes:
      - "keycloak-data:/var/lib/postgresql"
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "password"

      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HTTP_ENABLED: true

      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start --import-realm
    depends_on:
      - keycloak-postgres
    volumes:
      - "./keycloak:/opt/keycloak/data/import:ro"

  postgres:
    image: postgres:15.15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres-data:/var/lib/postgresql"

  redis:
    image: redis:8.4
    command: redis-server --requirepass password

  backend:
    image: ghcr.io/helpwave/tasks-backend:latest
    environment:
      DATABASE_HOSTNAME: "postgres"
      DATABASE_NAME: "postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "password"

      REDIS_HOSTNAME: "redis"
      REDIS_PASSWORD: "password"

      ISSUER_URI: "http://keycloak:8080/realms/tasks"
      PUBLIC_ISSUER_URI: "http://localhost:8080/realms/tasks"
      CLIENT_ID: "tasks-backend"
      CLIENT_SECRET: "tasks-secret"
      
      ENV: "development"
    depends_on:
      - postgres
      - redis

  web:
    image: ghcr.io/helpwave/tasks-web:latest
    environment:
      RUNTIME_ISSUER_URI: "http://localhost/keycloak/realms/tasks"
      RUNTIME_REDIRECT_URI: "http://localhost/auth/callback"
      RUNTIME_POST_LOGOUT_REDIRECT_URI: "http://localhost/"
      RUNTIME_CLIENT_ID: "tasks-web"
    depends_on:
      - backend

  proxy:
    image: ghcr.io/helpwave/tasks-proxy:latest
    environment:
      KEYCLOAK_HOST: keycloak:8080
      BACKEND_HOST: backend:80
      FRONTEND_HOST: web:80
    ports:
      - "80:80"
    depends_on:
      - keycloak
      - backend
      - web

volumes:
  keycloak-data:
  postgres-data:
