services:
  keycloak-postgres:
    image: postgres
    volumes:
      - "keycloak-postgres-data:/var/lib/postgresql"
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "password"

      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: "info"
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    depends_on:
      - keycloak-postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres-data:/var/lib/postgresql"

  backend:
    image: ghcr.io/helpwave/tasks-backend:latest
    restart: always
    environment:
      DATABASE_HOSTNAME: "postgres"
      DATABASE_NAME: "postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "password"

      ISSUER_URI: "http://keycloak:8080/realms/tasks"
      PUBLIC_ISSUER_URI: "http://localhost:8080/realms/tasks"
      CLIENT_ID: "tasks"
      CLIENT_SECRET: "tasks-secret"
    depends_on:
      - postgres

  web:
    image: ghcr.io/helpwave/tasks-web:latest
    restart: always
    environment:
      ISSUER_URI: "http://localhost:8080/realms/tasks"
      CLIENT_ID: "tasks"
    depends_on:
      - backend

  proxy:
    image: ghcr.io/helpwave/tasks-proxy:latest
    restart: always
    environment:
      BACKEND_HOST: backend:80
      FRONTEND_HOST: web:80
    ports:
      - "80:80"
    depends_on:
      - backend
      - web

volumes:
  keycloak-postgres-data:
  postgres-data:
