services:
  keycloak-postgres:
    image: postgres:15.15
    volumes:
      - "keycloak-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "password"

      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HTTP_ENABLED: true

      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start --import-realm
    depends_on:
      - keycloak-postgres
    volumes:
      - "./keycloak:/opt/keycloak/data/import:ro"

  postgres:
    image: postgres:15.15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  redis:
    image: redis:8.4
    command: redis-server --requirepass password

  influxdb:
    image: influxdb:2.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: tasks
      DOCKER_INFLUXDB_INIT_BUCKET: audit
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tasks-token-secret
    volumes:
      - "influxdb-data:/var/lib/influxdb2"

  backend:
    image: ghcr.io/helpwave/tasks-backend:latest
    environment:
      DATABASE_HOSTNAME: "postgres"
      DATABASE_NAME: "postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "password"

      REDIS_HOSTNAME: "redis"
      REDIS_PASSWORD: "password"

      ISSUER_URI: "http://keycloak:8080/keycloak/realms/tasks"
      PUBLIC_ISSUER_URI: "http://localhost/keycloak/realms/tasks"
      CLIENT_ID: "tasks-backend"
      CLIENT_SECRET: "tasks-secret"
      
      ENV: "development"
      SCAFFOLD_DIRECTORY: "/scaffold"

      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_TOKEN: "tasks-token-secret"
      INFLUXDB_ORG: "tasks"
      INFLUXDB_BUCKET: "audit"
    volumes:
      - "./scaffold:/scaffold:ro"
    depends_on:
      - postgres
      - redis
      - influxdb

  web:
    image: ghcr.io/helpwave/tasks-web:latest
    environment:
      RUNTIME_GRAPHQL_ENDPOINT: "http://localhost/graphql"
      RUNTIME_ISSUER_URI: "http://localhost/keycloak/realms/tasks"
      RUNTIME_REDIRECT_URI: "http://localhost/auth/callback"
      RUNTIME_POST_LOGOUT_REDIRECT_URI: "http://localhost/"
      RUNTIME_CLIENT_ID: "tasks-web"
    depends_on:
      - backend

  proxy:
    image: ghcr.io/helpwave/tasks-proxy:latest
    environment:
      KEYCLOAK_HOST: keycloak:8080
      BACKEND_HOST: backend:80
      FRONTEND_HOST: web:80
    ports:
      - "80:80"
    depends_on:
      - keycloak
      - backend
      - web

volumes:
  keycloak-data:
  postgres-data:
  influxdb-data:
